### ISSUE TITLE
Agenda 2024 kickoff meeting

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#1005]
2024年，近期会议记录

**Comment by jeremyjia** [comment]
- [ ] #1006

**Comment by jeremyjia** [comment]
https://www.cnblogs.com/qiumingcheng/p/6843053.html

**Comment by waynexw** [comment]
https://platform.openai.com/docs/guides/rate-limits?context=tier-free

**Comment by jeremyjia** [comment]
http://www.jianpu99.net/example.php

**Comment by jeremyjia** [comment]
ChatGPT API的连续会话能力
我们知道，官方的ChatGPT以及ChatGPT Plus最强的地方就在于它拥有上下文联系，也就是能跟你连续会话的能力，正因为如此，让你拥有了跟一个现实伴侣、导师或者朋友交谈的感觉。另外，这次的API自带连续对话能力，你只需在接口入参的地方将历史对话内容一并赋值给Message参数，回传给模型就可以。不过这势必会增加token的费用，这点有点坑啊。官方似乎也意识到了这点，所以，单次传的token上限为4096，超过4096会返回报错

**Comment by jeremyjia** [comment]
调用文心一言API的使用

**Comment by jeremyjia** [comment]
1/13/2024 会议记录 (Littleflute, jeremyjia, Wangxu）

**Comment by jeremyjia** [comment]
http://www.xiyangw.com/post/65708.html

**Comment by jeremyjia** [comment]
API, (templateURL, json)

**Comment by jeremyjia** [comment]
https://blog.csdn.net/weixin_46168640/article/details/121713164

**Comment by jeremyjia** [comment]
// data.put("textTag",new TextRenderData(c,
                        text));
                        data.put("textTag", Texts.of(text).color(c).fontSize(fontSize).create()); 
                        dataList.add(data);

**Comment by jeremyjia** [comment]
https://plantuml.com/zh/json

**Comment by jeremyjia** [comment]
堆：https://www.bilibili.com/video/BV1AF411G7cA/?spm_id_from=333.788

**Comment by jeremyjia** [comment]
求逆运算
剧本->word
word->剧本

**Comment by jeremyjia** [comment]
3/9/2024 会议记录 (Littleflute, jeremyjia, Wangxu）

**Comment by jeremyjia** [comment]
3/16/2024 会议记录 (Littleflute, jeremyjia）

**Comment by jeremyjia** [comment]
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
canvas {
    border:1px solid #d3d3d3;
    background-color: #f1f1f1;
}
</style>
</head>
<body onload="startGame()">
<script>

var myGamePiece;


function startGame() {
    myGameArea.start();
    myGamePiece = new component(30, 30, "green", 10, 120);
    const a = function(width, height, color, x, y){
    //return new component(30, 30, "red", 10, 160);
    var o={};
    
    o.width = width;
    o.height = height;
    o.x = x;
    o.y = y;    
    ctx = myGameArea.context;
    ctx.fillStyle = color;
    ctx.fillRect(o.x, o.y, o.width, o.height);
    
    return o;
    }(30,30, "red", 10, 160);
}

var myGameArea = {
    canvas : document.createElement("canvas"),
    start : function() {
        this.canvas.width = 490;
        this.canvas.height = 270;
        this.context = this.canvas.getContext("2d");
        document.body.insertBefore(this.canvas, document.body.childNodes[0]);
    }
}


function component(width, height, color, x, y) {
    this.width = width;
    this.height = height;
    this.x = x;
    this.y = y;    
    ctx = myGameArea.context;
    ctx.fillStyle = color;
    ctx.fillRect(this.x, this.y, this.width, this.height);
}

</script>

<p>We have added a component to our game, a red square!</p>

</body>
</html>

**Comment by jeremyjia** [comment]
https://jeremyjia.github.io/Games/node1/public/937/index.html

**Comment by jeremyjia** [comment]
以下实例可以做成Python插件
https://www.51cto.com/article/653823.html

**Comment by jeremyjia** [comment]
网易歌曲列表可以编辑

**Comment by waynexw** [comment]
Traceback (most recent call last):
  File "C:\Users\hasee\waynexw\Games\python\app.py", line 41, in <module>
    main()
  File "C:\Users\hasee\waynexw\Games\python\app.py", line 38, in main
    ciyun()
  File "C:\Users\hasee\waynexw\Games\python\app.py", line 16, in ciyun
    wc = WordCloud(width=1400, height=2200,
  File "C:\Users\hasee\AppData\Local\Programs\Python\Python39\lib\site-packages\wordcloud\wordcloud.py", line 642, in generate
    return self.generate_from_text(text)
  File "C:\Users\hasee\AppData\Local\Programs\Python\Python39\lib\site-packages\wordcloud\wordcloud.py", line 624, in generate_from_text
    self.generate_from_frequencies(words)
  File "C:\Users\hasee\AppData\Local\Programs\Python\Python39\lib\site-packages\wordcloud\wordcloud.py", line 511, in generate_from_frequencies
    box_size = draw.textbbox((0, 0), word, font=transposed_font, anchor="lt")
  File "C:\Users\hasee\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\ImageDraw.py", line 657, in textbbox
    bbox = font.getbbox(
AttributeError: 'TransposedFont' object has no attribute 'getbbox'

**Comment by jeremyjia** [comment]
4/6/2024 会议记录 (Littleflute, jeremyjia, Wangxu）
1. 调试词云图程序遇到上面的问题（Wangxu继续做一些调研）
2. Python插件展示，其中改进地方如下
      a. 素描插件，可以接受整个Mp4视频作为参数，输出为应用插件效果的视频
      b. 插件的引用方式可以更加灵活和跨库使用
3. 可以尝试自己实现词云图积累算法
4. 合理利用小程序

**Comment by jeremyjia** [comment]
setTimeout函数是JavaScript语言内置提供的一个全局函数，它的作用类似于定时器，指定一个时长和一个函数，等待这一段时长过后调用Func函数

**Comment by jeremyjia** [comment]
视频叠加命令
https://blog.csdn.net/vichild/article/details/107812938

**Comment by jeremyjia** [comment]
4/13/2024 会议记录 (Littleflute, jeremyjia）
1. 展示词云图app及插件的特效（继续调研一些问题）
2. 展示主页的歌曲播放清单添加功能（继续升级做到列表及时更新， 数据库更新是另一回事，对比天气预报它有用户的概念，用户的地区可以展示不同的效果，将此功能封装成小的组件需要考虑这个需求）
3. 新集能源股票K线图的分析，看涨策略，士兵探路策略等，（K线图是日本人发明的，表达了一个事物某个时间段，如一个季度的开始、结束、峰值、低谷值四项属性，可以借鉴到很多地方）

**Comment by jeremyjia** [comment]
4/20/2024 会议记录 (Littleflute, jeremyjia, Wangxu）
1. Game主页歌曲编辑功能展示，播放时能否显示网易云音乐的歌词（有点麻烦）
2. 词云程序扩展实现，类似虚拟网络摄像机初步的demo（wangxu继续增加红绿通道调节功能）

**Comment by jeremyjia** [comment]
https://blog.csdn.net/stormdony/article/details/82837623

**Comment by jeremyjia** [comment]
https://music.163.com/api/song/media?id=5232465

**Comment by jeremyjia** [comment]
the key is that it uses socks5h instead of socks5

**Comment by jeremyjia** [comment]
(Just a little reminder) If you want the hostname also be resolved by the proxy (that means passing everything through the proxy), especially when you are cloning a gist, you can use the following setting (the key is that it uses socks5h instead of socks5):

git config --global http.proxy socks5h://127.0.0.1:1080

**Comment by jeremyjia** [comment]
5/25/2024 会议记录 (Littleflute, jeremyjia）
演示ffmpeg实现画中画的效果及实现制定时间的叠加需求

**Comment by jeremyjia** [comment]
https://music.163.com/#/song?id=5232465

**Comment by jeremyjia** [comment]
ffmpeg -i background.mp4 -i overlay.mp4 -filter_complex "[1:v]scale=320:240[ov];[0:v][ov]overlay=10:10:enable='between(t,5,15)'" -c:a copy output.mp4

**Comment by jeremyjia** [comment]
参数解释
-i background.mp4：指定背景视频输入。
-i overlay.mp4：指定叠加视频输入。
-filter_complex：使用复杂过滤器。
[1:v]scale=320:240[ov]：将叠加视频缩放到320x240大小，并命名为ov。
[0:v][ov]overlay=10:10:enable='between(t,5,15)'：
[0:v]：背景视频。
[ov]：缩放后的叠加视频。
overlay=10:10：将叠加视频放置在背景视频的(10, 10)位置。
enable='between(t,5,15)'：仅在5秒到15秒之间启用叠加。
-c:a copy：直接复制音频流，而不进行重新编码。
output.mp4：输出文件名。

**Comment by jeremyjia** [comment]
ffmpeg -i s.mp4 -i overlay.mp4 -filter_complex "[1:v]scale=320:240[ov];[0:v][ov]overlay=10:10:enable='between(t,5,15)'" -c:a copy -max_muxing_queue_size 1024 output.mp4

**Comment by jeremyjia** [comment]
Airflow

**Comment by jeremyjia** [comment]
6/8/2024 会议记录 (Wangxu, jeremyjia）
1. ffmpeg画中画插件调试
2. 二维码生成试验
3. Undo/Redo试验

**Comment by jeremyjia** [comment]
# per_page=100
https://api.github.com/repos/jeremyjia/Games/issues/525/comments?per_page=100

**Comment by jeremyjia** [comment]
https://m10.music.126.net/20240608214152/5f99a40ece79d73df5bc8d5679a7d50f/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3094057196/4e14/219b/fd62/27371cc9c6924da6a75249559c528a47.mp3

**Comment by jeremyjia** [comment]
6/15/2024 会议记录 (Littleflute, jeremyjia）
1. 生命科学示例讨论，可以用2号寻路界面进行初始化设定，是否存在永动的状态
2. 光阴的故事及画中画展示及协议讨论
3. Undo的展示，Undo按钮模式，然后点击可以当前的场景
4. 精灵对象，剧本中增加做为普通的场景对象，script可以在剧本中引入或者直接写

**Comment by jeremyjia** [comment]
1. 后端看齐

**Comment by jeremyjia** [comment]
6/29/2024 会议记录 (Littleflute, jeremyjia）

**Comment by waynexw** [comment]
20240706：汇报二维码生成功能调研python QrCode
安装库 pip install qrcode[pil]
实现代码如下：
import argparse
import qrcode

def create_qr_code(input_text, output_file):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(input_text)
    qr.make(fit=True)

    img = qr.make_image(fill='black', back_color='white')
    img.save(output_file)
    print(f"QR code saved as {output_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate a QR code from input text")
    parser.add_argument('--input', '-i', help='Input text for QR code', required=True)
    parser.add_argument('--output', '-o', help='Output file name for the QR code image', required=True)

    args = parser.parse_args()

    create_qr_code(args.input, args.output)

在命令行运行脚本 python generate_qr.py --input "www.google.com" --output "google_qr.jpg"
这个.py 生成了" www.google.com"的QR code 并存储图片在相同的文件夹下，名字叫google_qr.jpg 如下
![image](https://github.com/jeremyjia/Games/assets/72367965/fc4fd190-ba20-4d13-9a56-6be3358dfe51)
我还实验了如下命令 python generate_qr.py --input "今天是个好日子" --output "hrz.jpg" 也生成了相应的QRcode如下
![image](https://github.com/jeremyjia/Games/assets/72367965/420edd8e-e617-4a52-abf7-d83d1cfa66c3)

**Comment by waynexw** [comment]
> 5/18/2024 会议记录 (Littleflute, jeremyjia, Wangxu 五一调休后的首次会议）
> 
> 1. 近期任务归纳
> 
> * [x]  词云图插件调试 （jeremyjia已调通，Wangxu可以学习一下）
> * [x]  二维码生成功能调研python QrCode（Wangxu）
> * [ ]  虚拟网络摄像机增加蓝绿通道调节选项 （Wangxu，模仿红通道实现）
> * [ ]  链接的在线编辑功能 （Wangxu，模仿网易歌曲编辑的实现方式,工作量较大）
> * [ ]  网易云音乐歌词提取并保存 （jeremyjia 参考：https://blog.csdn.net/stormdony/article/details/82837623 ）
> * [x]  画中画效果ffmpeg命令整理 (littleflute)
> * [x]  画中画效果及成到后端服务程序（jeremyjia）
> * [ ]  前端音符在线编辑 （littleflute）
> 
> 2. 音符网页端21号在线测试参考：[剧本中新增音乐简谱的音符对象 #993](https://github.com/jeremyjia/Games/issues/993)
> 3. socket5代理失效及其解决办法 the key is that it uses socks5h instead of socks5
>    https://stackoverflow.com/questions/15227130/using-a-socks-proxy-with-git-for-the-http-transport



> 5/18/2024 会议记录 (Littleflute, jeremyjia, Wangxu 五一调休后的首次会议）
> 
> 1. 近期任务归纳
> 
> * [x]  词云图插件调试 （jeremyjia已调通，Wangxu可以学习一下）
> * [x]  二维码生成功能调研python QrCode（Wangxu）
> * [ ]  虚拟网络摄像机增加蓝绿通道调节选项 （Wangxu，模仿红通道实现）
> * [ ]  链接的在线编辑功能 （Wangxu，模仿网易歌曲编辑的实现方式,工作量较大）
> * [ ]  网易云音乐歌词提取并保存 （jeremyjia 参考：https://blog.csdn.net/stormdony/article/details/82837623 ）
> * [x]  画中画效果ffmpeg命令整理 (littleflute)
> * [x]  画中画效果及成到后端服务程序（jeremyjia）
> * [ ]  前端音符在线编辑 （littleflute）
> 
> 2. 音符网页端21号在线测试参考：[剧本中新增音乐简谱的音符对象 #993](https://github.com/jeremyjia/Games/issues/993)
> 3. socket5代理失效及其解决办法 the key is that it uses socks5h instead of socks5
>    https://stackoverflow.com/questions/15227130/using-a-socks-proxy-with-git-for-the-http-transport

二维码生成功能：https://github.com/jeremyjia/Games/issues/1027#issuecomment-2210757730

**Comment by jeremyjia** [comment]
7/06/2024 会议记录 (Littleflute, jeremyjia）

**Comment by jeremyjia** [comment]
7/13/2024 会议记录 (Littleflute, jeremyjia）
failed to connect to Live Share: error connecting websocket: websocket: bad handshake

**Comment by jeremyjia** [comment]
https://code.visualstudio.com/docs/cpp/introvideos-cpp

**Comment by jeremyjia** [comment]
https://docs.github.com/zh/codespaces
https://github.com/zyronon/douyin

**Comment by jeremyjia** [comment]
7/20/2024 会议记录 (Littleflute, jeremyjia, Wangxu）
1.https://github.com/zyronon/douyin
2.闲聊话题

**Comment by jeremyjia** [comment]
failed to connect to Live Share: timed out while waiting for the codespace to start

**Comment by jeremyjia** [comment]
https://api.cntv.cn/olympic/getOlyMedals?serviceId=pcocean&itemcode=GEN-------------------------------&t=jsonp&cb=omedals1

**Comment by jeremyjia** [comment]
8/3/2024 会议记录 (Littleflute, jeremyjia, Wangxu）
1. 巴黎奥运会金牌榜插件案例展示
2. 二维码插件会上进行调试（if __name__ == "__main__":）
    python的命名需要注意，如果与某个库函数同名的话，又刚好import它，就会相当于优先引用了这个文件本身，会遇到奇怪的错误

**Comment by jeremyjia** [comment]
# python常用命令总结

**Comment by jeremyjia** [comment]
9/7/2024 会议记录 (Littleflute, jeremyjia）

**Comment by jeremyjia** [comment]
需求记录：UI编辑器可以显示与后端服务的连接状态

**Comment by jeremyjia** [comment]
9/14/2024 会议记录 (Littleflute, jeremyjia, Wangxu）

**Comment by jeremyjia** [comment]
BUG:超级对象的文本换行问题需要改进

**Comment by jeremyjia** [comment]
var obj = document.getElementById('a123jia');
obj.onclick = function(){
alert(this.id);

}

**Comment by jeremyjia** [comment]
9/21/2024 会议记录 (Littleflute, jeremyjia, Wangxu）
1. 演示上次会议的任务列表
2. 沙盒演示后门程序
3. UI编辑器视频制作进度剩余时间估计（TBD）

**Comment by jeremyjia** [comment]
- [ ] #1125

**Comment by jeremyjia** [comment]
WebAssembly c++ & figma

**Comment by jeremyjia** [comment]
# 1126

**Comment by jeremyjia** [comment]
https://www.jb51.net/article/253089.htm

**Comment by jeremyjia** [comment]
http://www.jianpuw.com/

**Comment by jeremyjia** [comment]
10/26/2024 会议记录 (Littleflute, jeremyjia, Wangxu)
1. 演示十一期间完成的一些features
2. 布置近期工作
3. 调查Release API上传功能(jeremyjia)
4. 测试用例的单元测试框架
5. 墙对象，股票等

**Comment by jeremyjia** [comment]
DECLARE @json NVARCHAR(MAX);

SET @json='{ 
"name": "Tom", 
"age": 35, 
"skills": [ "SQL", "C#", "MVC" ],
"Data": [
{"SQL":1, "Python":2, "Java":3, "CVXCD":[{"a1":15, "6. Conv. / Exer. Rate":3.8,"a3":7.21}]}，
{"SQL":1, "Python":2, "Java":3, "CVXCD":[{"a1":15, "6. Conv. / Exer. Rate":3.9,"a3":7.21}]}
]
}';

SELECT A.Identifier, A.CVXCD
FROM OPENJSON(@json,'$.Data')
	WITH (
		Identifier NVARCHAR(255) '$.SQL'
		,ISSRCD NVARCHAR(255) '$.Java'
		,CVXCD NVARCHAR(255) '$.CVXCD[0]."6. Conv. / Exer. Rate"'
	) A



	select ConversionRatio from MxSec.SecMaster

**Comment by jeremyjia** [comment]
# 视频素材网站
https://www.pexels.com/zh-cn/

**Comment by jeremyjia** [comment]
素材准备
1. VOA英语
2. 毛泽东选集
3. 猫咪的日常
4. 程序设计，效果演示，如生日烟花

**Comment by jeremyjia** [comment]
# create a token
https://github.com/settings/personal-access-tokens/new

**Comment by jeremyjia** [comment]
# 新概念课文及LRC下载
https://www.tingclass.net/show-5025-7-1.html

**Comment by jeremyjia** [comment]
# 测试用例
java -cp "./lib*:JavaStudy-0.0.3-SNAPSHOT.jar" Main

**Comment by jeremyjia** [comment]
Python mplfinance库：金融数据可视化

**Comment by jeremyjia** [comment]
生日蛋糕

**Comment by jeremyjia** [comment]
11/30/2024 会议记录 (Littleflute, jeremyjia, Wangxu）

**Comment by jeremyjia** [comment]
https://stock.finance.sina.com.cn/usstock/quotes/AAPL.html

**Comment by jeremyjia** [comment]
Tushare

**Comment by jeremyjia** [comment]
中国石油
https://finance.sina.com.cn/realstock/company/sh601857/nc.shtml

**Comment by jeremyjia** [comment]
https://blog.csdn.net/weixin_55154866/article/details/128981685?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-5-128981685-blog-129764721.235^v43^pc_blog_bottom_relevance_base7&spm=1001.2101.3001.4242.4&utm_relevant_index=7

**Comment by jeremyjia** [comment]
# 回归
https://blog.csdn.net/qq_41780234/article/details/135045125

**Comment by jeremyjia** [comment]
downgrade to 'numpy<2' 的含义与操作‌
‌含义‌：
该建议意味着，如果你的程序或使用的模块与NumPy 2.x版本不兼容，导致程序崩溃或无法正常运行，一个简单的解决方案是将NumPy版本降级到2.x以下的版本（即1.x版本），以确保程序的稳定性和兼容性。
‌操作指南‌：
‌查询当前NumPy版本‌：
使用命令 pip show numpy 来查看当前安装的NumPy版本。
‌卸载当前NumPy版本‌：
若当前版本为2.x，且需要降级，则先卸载当前版本，使用命令 pip uninstall numpy。
‌选择并安装合适的NumPy 1.x版本‌：
使用命令 pip index versions numpy 查看可用的NumPy版本。
选择一个合适的1.x版本，例如 numpy==1.19.5，然后使用命令 pip install numpy==1.19.5 进行安装。
‌验证安装‌：
再次使用 pip show numpy 确认已安装的版本。
运行程序或模块，检查是否还存在兼容性问题。

**Comment by jeremyjia** [comment]
12/14/2024 会议记录 (Littleflute, jeremyjia）
1. 展示股票K线图插件及真实的股票历史数据插件
2. 需要继续升级，绘制均线图，小时K线图（TODO）
3. 和弦派、SunoAI、随身乐队（黄老师最近买了会员）
4. 使用和弦派在线制作了软件会议的歌词测试

**Comment by jeremyjia** [comment]
BaoStock是一个免费开源的证券数据平台，它提供的数据包括日、周、月K线数据以及5、15、30、60分钟K线数据，但这些K线数据的时间范围是从1999年7月26日至今，并不包括交易当天的实时数据‌

**Comment by jeremyjia** [comment]
要获取当天实时小时K线的免费API，有几个选择可以考虑：
‌首先，AllTick API提供了一个实时股票Tick数据API，支持查询分钟K线数据‌。用户可以通过更改kline_type参数来获取不同类型的K线数据，包括小时K线。这是一个免费的选择，但可能需要注册和获取API秘钥才能使用‌1。
‌其次，iTick也提供了免费的实时指数报价API接口‌，其中包括K线数据。用户可以通过发送HTTP请求来获取指定指数的小时K线数据。同样，这可能需要注册和认证才能访问‌2。
除了上述两个专门的金融数据API提供商外，‌还有一些其他的免费金融数据平台或网站也可能提供实时的小时K线数据‌。例如，一些在线金融新闻网站和应用，如Yahoo Finance，可能提供免费的市场数据更新，包括实时价格和小时K线图表。然而，这些数据的质量和深度可能无法与专业金融数据服务平台相媲美‌3。
需要注意的是，虽然这些API是免费的，但它们可能有使用限制，如请求频率、数据精度或访问量等。此外，免费API的数据质量和实时性也可能不如付费的API。因此，在选择使用免费API时，需要根据自己的需求和期望进行权衡。
总的来说，‌AllTick API和iTick是获取当天实时小时K线数据的两个免费选择‌。用户可以根据自己的需求和偏好选择合适的API，并遵循相应的注册和使用流程来获取数据。

**Comment by jeremyjia** [comment]
https://www.95sca.cn/archives/45917

**Comment by jeremyjia** [comment]
12/21/2024 会议记录 (Littleflute, jeremyjia, Wangxu）
